# Generated by Django 2.2.4 on 2019-10-23 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20191023_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='context',
            new_name='content',
        ),
    ]
